"""
Tests that demonstarte the usage of the clock_in_clock_out module.
"""

import os
import pytest

import clock_in_clock_out as cc


def test_control_records(small_xml):
    """Test the aggregated time for control records baked in the
    sample data XML file generated by the fixture."""
    ts = cc.query(small_xml, start='31-12-2018', end='31-12-2018', names=True)
    control = ts.loc[ts.full_name=='h.simpson', 'time'].iloc[0]
    assert control == 10