"""
Tests that demonstarte the usage of the clock_in_clock_out package.
"""

import os
import pytest

import clock_in_clock_out as cc


def test_control_records(small_xml):
    """Test the aggregated time for control records baked in the
    sample data XML file generated by the fixture."""
    timesheet = cc.query(small_xml, start_date='31-12-2018',
                         end_date='31-12-2018', incl_names=True)
    control = timesheet.loc[timesheet.full_name=='h.simpson', 'time'].iloc[0]
    assert control == 10